'use server'

import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { getCurrentUser } from '@/lib/db/server'
import {
  analyseStored, canIngest, commitIngestion, createUploadTarget,
} from '@/lib/ingest/commit'
import { consumeRateLimit } from '@/lib/rate-limit'
import { MAX_BATCH } from '@/lib/ingest/constants'
import type { ParsedDocument } from '@/lib/ingest/parse-ctis'

/**
 * Storage keys are generated by createUploadTarget() in exactly this shape.
 * Validating against the shape rather than a `startsWith` prefix keeps traversal
 * segments and stray path characters out of the Storage API.
 */
const STORAGE_KEY_RE = /^ingest\/\d{4}\/[0-9a-f-]{36}-[A-Za-z0-9._-]{1,80}$/

async function requireIngestor() {
  const user = await getCurrentUser()
  if (!user) return { error: 'You are not signed in.' as const }
  if (!canIngest(user.team)) {
    return { error: 'Your team is not permitted to file documents into the repository.' as const }
  }
  return { user }
}

export interface UploadTarget {
  error?: string
  storageKey?: string
  token?: string
}

/**
 * Step 1. Hands the browser a one-shot signed URL so the file goes straight to
 * Storage — the bytes never cross this server, which keeps us clear of host
 * request-body limits.
 */
export async function createUploadTargetAction(fileName: string): Promise<UploadTarget> {
  const gate = await requireIngestor()
  if ('error' in gate) return { error: gate.error }

  const limited = await consumeRateLimit(`ingest:upload:${gate.user.id}`, 20, 300)
  if (!limited.allowed) {
    return { error: `Too many uploads. Try again in ${limited.retryAfterSeconds} seconds.` }
  }

  if (typeof fileName !== 'string' || fileName.length === 0 || fileName.length > 255) {
    return { error: 'That file name is not usable.' }
  }

  const target = await createUploadTarget(fileName)
  if (!target.ok) return { error: target.error }

  return { storageKey: target.storageKey, token: target.token }
}

export interface AnalyseState {
  error?: string
  storageKey?: string
  fileName?: string
  pageCount?: number
  parsed?: ParsedDocument
}

/**
 * Step 2. Reads the uploaded object back, validates it is really a text-layer
 * PDF, and returns the extraction for review. Nothing is written to the
 * repository.
 */
export async function analyseStoredAction(
  storageKey: string,
  fileName: string,
): Promise<AnalyseState> {
  const gate = await requireIngestor()
  if ('error' in gate) return { error: gate.error }

  const limited = await consumeRateLimit(`ingest:analyse:${gate.user.id}`, 20, 300)
  if (!limited.allowed) {
    return { error: `Too many uploads. Try again in ${limited.retryAfterSeconds} seconds.` }
  }

  if (typeof storageKey !== 'string' || !STORAGE_KEY_RE.test(storageKey)) {
    return { error: 'The upload reference is malformed. Start again.' }
  }

  const result = await analyseStored(storageKey)
  if (!result.ok) return { error: result.error }

  return {
    storageKey: result.storageKey,
    fileName,
    pageCount: result.pageCount,
    parsed: result.parsed,
  }
}

const overridesSchema = z.array(
  z.object({
    considerationNumber: z.number().int().positive(),
    category: z.string().max(60).optional(),
    memberState: z.string().length(2).nullable().optional(),
  }),
)

const commitItemSchema = z.object({
  storageKey: z.string().regex(STORAGE_KEY_RE, 'The upload reference is malformed'),
  overrides: overridesSchema.default([]),
})

const commitBatchSchema = z
  .array(commitItemSchema)
  .min(1, 'Nothing to file')
  .max(MAX_BATCH, `Up to ${MAX_BATCH} documents at a time`)

export interface FiledDocument {
  storageKey: string
  documentRef: string
  trialNumber: string
  considerationCount: number
  overriddenCount: number
}

export interface RejectedDocument {
  storageKey: string
  error: string
}

export interface CommitState {
  error?: string
  filed?: FiledDocument[]
  rejected?: RejectedDocument[]
}

/**
 * Step 3. The reviewer approves; only now does anything reach the repository.
 *
 * Documents are filed one at a time and reported one at a time. A batch of four
 * where the second is a duplicate files the other three and says so — refusing
 * all four because of one would be worse for the user and no safer, since each
 * document is already independently atomic inside commitIngestion(). There is no
 * transaction spanning them and there should not be: they are separate records
 * that happened to be uploaded together.
 */
export async function commitAction(
  _prev: CommitState,
  formData: FormData,
): Promise<CommitState> {
  const gate = await requireIngestor()
  if ('error' in gate) return { error: gate.error }

  const limited = await consumeRateLimit(`ingest:commit:${gate.user.id}`, 30, 300)
  if (!limited.allowed) {
    return { error: `Too many attempts. Try again in ${limited.retryAfterSeconds} seconds.` }
  }

  const raw = formData.get('documents')
  if (typeof raw !== 'string' || !raw.trim()) {
    return { error: 'Nothing to file. Start again.' }
  }

  // JSON.parse throws on malformed input; unguarded it crashes the action.
  let decoded: unknown
  try {
    decoded = JSON.parse(raw)
  } catch {
    return { error: 'Your corrections could not be read. Start again.' }
  }

  const parsed = commitBatchSchema.safeParse(decoded)
  if (!parsed.success) {
    return { error: parsed.error.issues[0].message }
  }

  const filed: FiledDocument[] = []
  const rejected: RejectedDocument[] = []

  for (const item of parsed.data) {
    const result = await commitIngestion({
      storageKey: item.storageKey,
      actorId: gate.user.id,
      actorTeam: gate.user.team!,
      overrides: item.overrides,
    })

    if (result.ok) {
      filed.push({
        storageKey: item.storageKey,
        documentRef: result.documentRef,
        trialNumber: result.trialNumber,
        considerationCount: result.considerationCount,
        overriddenCount: result.overriddenCount,
      })
    } else {
      rejected.push({ storageKey: item.storageKey, error: result.error })
    }
  }

  if (filed.length > 0) revalidatePath('/search')

  return { filed, rejected }
}
