'use server'

import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { getCurrentUser } from '@/lib/db/server'
import {
  analyseStored, canIngest, commitIngestion, createUploadTarget,
} from '@/lib/ingest/commit'
import { rateLimit } from '@/lib/rate-limit'
import type { ParsedDocument } from '@/lib/ingest/parse-ctis'

/**
 * Storage keys are generated by createUploadTarget() in exactly this shape.
 * Validating against the shape rather than a `startsWith` prefix keeps traversal
 * segments and stray path characters out of the Storage API.
 */
const STORAGE_KEY_RE = /^ingest\/\d{4}\/[0-9a-f-]{36}-[A-Za-z0-9._-]{1,80}$/

async function requireIngestor() {
  const user = await getCurrentUser()
  if (!user) return { error: 'You are not signed in.' as const }
  if (!canIngest(user.team)) {
    return { error: 'Your team is not permitted to file documents into the repository.' as const }
  }
  return { user }
}

export interface UploadTarget {
  error?: string
  storageKey?: string
  token?: string
}

/**
 * Step 1. Hands the browser a one-shot signed URL so the file goes straight to
 * Storage — the bytes never cross this server, which keeps us clear of host
 * request-body limits.
 */
export async function createUploadTargetAction(fileName: string): Promise<UploadTarget> {
  const gate = await requireIngestor()
  if ('error' in gate) return { error: gate.error }

  const limited = rateLimit(`ingest:upload:${gate.user.id}`, 20, 300)
  if (!limited.allowed) {
    return { error: `Too many uploads. Try again in ${limited.retryAfterSeconds} seconds.` }
  }

  if (typeof fileName !== 'string' || fileName.length === 0 || fileName.length > 255) {
    return { error: 'That file name is not usable.' }
  }

  const target = await createUploadTarget(fileName)
  if (!target.ok) return { error: target.error }

  return { storageKey: target.storageKey, token: target.token }
}

export interface AnalyseState {
  error?: string
  storageKey?: string
  fileName?: string
  pageCount?: number
  parsed?: ParsedDocument
}

/**
 * Step 2. Reads the uploaded object back, validates it is really a PDF, and
 * returns the extraction for review. Nothing is written to the repository.
 */
export async function analyseStoredAction(
  storageKey: string,
  fileName: string,
): Promise<AnalyseState> {
  const gate = await requireIngestor()
  if ('error' in gate) return { error: gate.error }

  const limited = rateLimit(`ingest:analyse:${gate.user.id}`, 20, 300)
  if (!limited.allowed) {
    return { error: `Too many uploads. Try again in ${limited.retryAfterSeconds} seconds.` }
  }

  if (typeof storageKey !== 'string' || !STORAGE_KEY_RE.test(storageKey)) {
    return { error: 'The upload reference is malformed. Start again.' }
  }

  const result = await analyseStored(storageKey)
  if (!result.ok) return { error: result.error }

  return {
    storageKey: result.storageKey,
    fileName,
    pageCount: result.pageCount,
    parsed: result.parsed,
  }
}

const overridesSchema = z.array(
  z.object({
    considerationNumber: z.number().int().positive(),
    category: z.string().max(60).optional(),
    memberState: z.string().length(2).nullable().optional(),
  }),
)

export interface CommitState {
  error?: string
  success?: {
    documentRef: string
    trialNumber: string
    considerationCount: number
    overriddenCount: number
  }
}

/** Step 3. The reviewer approves; only now does anything reach the repository. */
export async function commitAction(
  _prev: CommitState,
  formData: FormData,
): Promise<CommitState> {
  const gate = await requireIngestor()
  if ('error' in gate) return { error: gate.error }

  const limited = rateLimit(`ingest:commit:${gate.user.id}`, 30, 300)
  if (!limited.allowed) {
    return { error: `Too many attempts. Try again in ${limited.retryAfterSeconds} seconds.` }
  }

  const storageKey = formData.get('storageKey')
  if (typeof storageKey !== 'string' || !STORAGE_KEY_RE.test(storageKey)) {
    return { error: 'The upload reference is missing or malformed. Start again.' }
  }

  let overrides: z.infer<typeof overridesSchema> = []
  const raw = formData.get('overrides')
  if (typeof raw === 'string' && raw.trim()) {
    // JSON.parse throws on malformed input; unguarded it crashes the action.
    let decoded: unknown
    try {
      decoded = JSON.parse(raw)
    } catch {
      return { error: 'Your corrections could not be read. Start again.' }
    }
    const parsed = overridesSchema.safeParse(decoded)
    if (!parsed.success) return { error: 'Your corrections could not be read. Start again.' }
    overrides = parsed.data
  }

  const result = await commitIngestion({
    storageKey,
    actorId: gate.user.id,
    actorTeam: gate.user.team!,
    overrides,
  })

  if (!result.ok) return { error: result.error }

  revalidatePath('/search')

  return {
    success: {
      documentRef: result.documentRef,
      trialNumber: result.trialNumber,
      considerationCount: result.considerationCount,
      overriddenCount: result.overriddenCount,
    },
  }
}
